# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'youtubeapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for youtubeapp
  pod 'RxSwift','~> 5.1.0'
  pod 'RxCocoa','~> 5.1.0'
  pod 'AlamofireImage'
  pod 'Alamofire'
  pod 'youtube-ios-player-helper-swift'

  target 'youtubeappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'youtubeappUITests' do
    # Pods for testing
  end

end
